angular.module('money', [
	//vendor stuff
	'ngAnimate',
	'ui.bootstrap',
	'ui.router',
	'luegg.directives',
	//autogenerated
	'templates',
	//our stuff
	'home',
	'day',
	'month',
	'year',
	'settings'
]);
